server:
  port: 10010
spring:
  application:
    name: pet-gateway
eureka:
  client:
    registry-fetch-interval-seconds: 5
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
zuul:
  add-host-header: true
  host:
    connect-timeout-millis: 15000
    socket-timeout-millis: 60000
  prefix: /api #路由路径的前缀
  routes:
    user-service:
      path: /user/** #用户服务的映射路径
      url: http://localhost:8081/
    pet-service:
      path: /pet/** #商品服务的映射路径
      url: http://localhost:8083/
  ribbon-isolation-strategy: semaphore
  semaphore:
    max-semaphores: 20

