server:
  port: 8081
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://139.196.254.75:3306/pet?Unicode=true&characterEncoding=utf8
    username: root
    password: mysql123456
    hikari:
      max-lifetime: 1800000
      maximum-pool-size:  10
    driver-class-name: com.mysql.jdbc.Driver
  #配置使用的缓存类型
  cache:
    type: redis
    cache-names: redisCache
  redis:
    #Redis服务器地址，默认localhost
    host: 39.97.175.10
    #Redis服务器端口，默认6379
    port: 6379
    #连接超时时间
    timeout: 1000
    #使用jedis的连接池
    jedis:
      pool:
        #连接池最大连接数
        max-active: 8
        #最大阻塞等待时间，-1表示没有限制
        max-wait: -1
        #最大空闲连接
        max-idle: 8
        #最小空闲连接
        min-idle: 0
    password: 123456
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
#    fetch-registry: false
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
feign:
  client:
    config:
      default:
        connectTime: 10000  # 链接时间
        readTimeOut: 10000  # 链接超时时间配置
      #日志级别的指定
      pet-service:
        loggerLeval: FULL
  logging:
    leval:
      com.pet.user.feign.ProductFeignClient: debug
#请求时间压缩 支持对请求和响应的GZIP的压缩，可以减少通信过程中的性能损耗
  compression:
    request:
      enabled: true # 开启请求压缩
      mime-types: text/html,application/yml,application/json
      min-request-size: 2048 #设置触发压缩的大小的下限。
    response:
      enabled: true # 开启相应压缩
ribbon:
  eureka:
    enabled: true